package org.churchcrm.churchcrmapi.identity.internal;

import org.churchcrm.churchcrmapi.identity.UserDto;
import org.churchcrm.churchcrmapi.identity.CreateUserDto;
import org.churchcrm.churchcrmapi.identity.UserCreated;
import org.churchcrm.churchcrmapi.organization.ChurchCreated;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.UUID;

/**
 * MapStruct mapper for User.
 */
@Mapper(componentModel = "spring")
public interface UserMapper {

    /**
     * Converts entity to DTO.
     * Automatically maps audit fields (createdAt, updatedAt, etc.)
     */
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "updatedBy", ignore = true)
    UserDto toDto(User entity);

    @Mapping(target = "fullname", source = "fullName")
    @Mapping(target = "username", source = "userName")
    CreateUserDto toDto(ChurchCreated event);

    /**
     * Converts Create DTO to entity.
     * Ignores id and audit (auto-generated by JPA auditing).
     * Uses Keycloak user ID as primary key.
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "audit", ignore = true)
    @Mapping(target = "churchId", source = "churchId")
    User toEntity(CreateUserDto dto, UUID churchId);

    /**
     * Converts entity to UserCreated event for church creation.
     */
    @Mapping(target = "id", source = "id")
    @Mapping(target = "entityName", source = "username")
    @Mapping(target = "username", source = "username")
    @Mapping(target = "fullname", source = "fullname")
    @Mapping(target = "email", source = "email")
    @Mapping(target = "churchId", source = "churchId")
    UserCreated toUserCreated(User entity);

    @Mapping(target = "entityName", ignore = true)
    @Mapping(target = "occurredAt", ignore = true)
    UserCreated toUserCreated(UserDto created);
}